name: CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in EC2 server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.SSH_USER }}
          script: |
            sudo docker stop shop-server-container
            sudo docker rm shop-server-container
            cd shop-server
            git pull
            cd ..
            sudo docker build -t shop-server:latest .
            sudo docker run -d --name shop-server-container -p 8080:8080 shop-server:latest
